### PR TITLE
change groupnames to use underscores, inventory_hostname instead of ansible_fqdn

### PR DESCRIPTION
**Pull request by twatts-redhat**

### CODE REVIEW

**Review by itewk — DISMISSED** [review]

**Comment by itewk** [comment]
looks good to me, want @bparry02 to take a look.

**Comment by bparry02** [comment]
@twatts-redhat Please update the README with new **Required groups**

It doesn't look like the following playbooks were updated for OCP 3.11 yet. That's OK, but I'll create an issue to do that and update the group names in those playbooks.

- playbooks/ocp-services-start.yml
- playbooks/ocp-services-stop.yml
- playbooks/ocp-hosts-shutdown.yml

**Review by bparry02 — CHANGES_REQUESTED** [review]
Requesting readme update but otherwise approved.

**Comment by bparry02** [comment]
Created #12 to track changes needed to other three playbooks.

**Review by bparry02 — APPROVED** [review]

**Pull request merged**
